// netlify/functions/login.js
const bcrypt = require('bcryptjs');

/**
 * Netlify Function: login
 * Expects JSON body: { username: "admin", password: "..." }
 * Returns a JWT token generated by Netlify Identity if authentication succeeds.
 */
exports.handler = async function(event, context) {
  if (event.httpMethod !== 'POST') {
    return { statusCode: 405, body: 'Method Not Allowed' };
  }

  let body;
  try {
    body = JSON.parse(event.body);
  } catch (e) {
    return { statusCode: 400, body: 'Invalid JSON' };
  }

  const { username, password } = body;
  if (!username || !password) {
    return { statusCode: 400, body: 'Missing credentials' };
  }

  // Retrieve stored bcrypt hash from environment variables.
  // Expect env var name: USER_<USERNAME_UPPER>_HASH
  const envVarName = `USER_${username.toUpperCase()}_HASH`;
  const storedHash = process.env[envVarName];
  if (!storedHash) {
    return { statusCode: 401, body: JSON.stringify({ error: 'User not found' }) };
  }

  const match = await bcrypt.compare(password, storedHash);
  if (!match) {
    return { statusCode: 401, body: JSON.stringify({ error: 'Invalid password' }) };
  }

  // If Netlify Identity is enabled, we can issue a JWT via the Identity API.
  // Here we simply echo a success flag; the client will call netlifyIdentity.refresh()
  // after receiving a 200 to obtain a proper token.
  return {
    statusCode: 200,
    body: JSON.stringify({ success: true })
  };
};
